version: '3.3'

services:
  super-cinema:
    image: lbertas1/super-cinema
    restart: always
    ports:
      - "8090:8090"
    networks:
      - super-cinema

  database:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_new_password
      MYSQL_DATABASE: super_cinema
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307
    networks:
      - super-cinema
      
volumes:
  mysql:
      
networks:
  super-cinema:
